<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\NotificationService.Shared\NotificationService.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Elasticsearch" />
    <PackageReference Include="Vonage" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Infrastructure library providing database access, Hangfire job execution, logging integrations (Serilog/ElasticSearch), and external gateway communication (Vonage/MailKit) for the Notification Service.</Description>
  </PropertyGroup>

</Project>
